### ISSUE TITLE
DeliveryCount?

### ISSUE THREAD

**Issue by antonioschaffert** [Azure/azure-functions-python-library#23]
Does the Python implementation not have a message delivery count like Node or C#?

See example of other implementations:

https://docs.microsoft.com/en-us/javascript/api/@azure/service-bus/servicebusmessage?view=azure-node-latest#deliverycount

**Comment by jeffhollan** [comment]
Thanks - looking into this

**Comment by ferantivero** [comment]
@maiqbal11 I've just required 1.0.4 (#26) + installed core tools 1633 (Azure/azure-functions-core-tools/pull/1552), but I'm still getting the following exception message:

`Exception: AttributeError: 'ServiceBusMessage' object has no attribute 'delivery_count'`

What I'm missing here?

**Comment by maiqbal11** [comment]
@ferantivero, the core tools that was released two days ago is from the previous sprint. @gzuber should be doing a release of the latest core tools soon. That will have the `delivery_count` changes.

**Comment by ferantivero** [comment]
Thanks for the info @maiqbal11, just for your information in the core tools I’ve installed (two days ago) I’m already seeing Azure/azure-functions-core-tools/pull/1552
