### ISSUE TITLE
Auto-Args to main in Azure function App are not generated at new bindings

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-functions-python-library#60]
@srikkar commented on [Mon Mar 16 2020](https://github.com/Azure/azure-sdk-for-python/issues/10330)

- **Package Name**:  Azure func core tools 
- **Package Version**: 2.7.2254
- **Operating System**: Windows
- **Python Version**:  3.6

**Describe the bug**
Have followed this URL: https://docs.microsoft.com/en-us/azure/python/tutorial-vs-code-serverless-python-07 to get the auto bindings generated. But, still after following the steps, I couldn’t get the auto generated arguments 

**To Reproduce**
1.  Follow the Steps as per URL above for Cosmos DB in binding with HTTPTrigger

**Expected behavior**
After Adding the new in binding to HTTPTrigger Azure function, expect SDK to auto-generate Args to access the data from Cosmos Graph/SQL inside function's main 

![Azure python binding Args](https://user-images.githubusercontent.com/29890085/76819443-0bfbd980-686d-11ea-8e4b-62f01fe1fa67.jpg)

**Additional context**
Any suggestions to get the data from grapgh DB using Gremlin API are most welcome

---

@msftbot[bot] commented on [Tue Mar 17 2020](https://github.com/Azure/azure-sdk-for-python/issues/10330#issuecomment-600215086)

Thanks for the feedback! We are routing this to the appropriate team for follow-up. cc @ahmedelnably, @fabiocav.

**Comment by ijoosong** [comment]
Here's a quick snippet that might help that uses the Gremlin API from Python Functions:
in __init__.py
`import logging
import azure.functions as func
import ast
from ..shared_code import config
from gremlin_python.driver import client, serializer


def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    if req.method == "POST":
        byte_body = req.get_body()
        logging.info(thi)
        dict_body = ast.literal_eval(byte_body.decode("UTF-8"))

        f_p = dict_body['fp']
        s_p = dict_body['sp']

        try:
            x = client.Client('wss://' + config.endpoint + ':443/', 'g',
                                username='/dbs/' + config.database + '/colls/' + config.collection,
                                password=config.password,
                                message_serializer=serializer.GraphSONSerializersV2d0()
                                )
            
            query = f"g.V('{f_p}').addE('knows').to(g.V('{s_p}'))"
            logging.info("\tRunning this Grem query:\n\t{0}\n".format(query))

            callback = x.submitAsync(query)
            if callback.result() is not None:
                logging.info("\tInserted this edge: \n\t{0}\n".format(callback.result().one()))
            else:
                logging.info("Something went wrong")
        except Exception as e:
            logging.info("there was an exception: {0}".format(e))
        return func.HttpResponse(f"Hello {f_p}")
`

my function.json looks like this:
`
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ]
}
`

and then take a look here: https://github.com/Azure-Samples/azure-cosmos-db-graph-python-getting-started/blob/master/connect.py

Hope this helps!

**Comment by stefanushinardi** [comment]
Will route this VS Code Extension

**Comment by shreyabatra4** [comment]
Routed to VS Code
