### ISSUE TITLE
Service Bus Batch Trigger

### ISSUE THREAD

**Issue by jrgcubano** [Azure/azure-functions-python-library#66]
There is any possibility to add the batch processing feature to service bus (Topics and Queues) as the .NET version (https://github.com/Azure/azure-functions-servicebus-extension/issues/15)?

I think you already have something implemented for EventHub:
- https://github.com/Azure/azure-functions-python-library/blob/dev/azure/functions/eventhub.py
- https://github.com/Azure/azure-functions-python-worker/issues/411

Thanks in advance

**Comment by Hazhzeng** [comment]
Thanks @jrgcubano for the suggestion, we're currently working on this feature now.

cc: @anirudhgarg @vrdmr
