### ISSUE TITLE
Multiple Output Messages to Service Bus

### ISSUE THREAD

**Issue by chielpeters90** [Azure/azure-functions-python-library#79]
For the Queue output binding it is possible to send multiple messages to the same output, see [Azure Documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue-output?tabs=python). In a similar fashion I would like to be able to do the same for Service Bus Messages.

My use case is to implement an Azure Function based on a timer which scrapes some data from an API and sends multiple messages to the same service bus topic. In a very basic example my function would look like this

**\_\_init\_\_.py**
```
import typing
import azure.functions as func

def main(mytimer: func.TimerRequest, outputmessage: func.Out[typing.List[str]]):
    outputmessage.set(["Message 1","Message 2"])
```

**function.json**
```
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "mytimer",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 */1 * * * *"
    },
    {
      "type": "serviceBus",
      "direction": "out",
      "connection": "AzureServiceBusConnectionString",
      "name": "outputmessage",
      "topicName": "mytopic2"
    }
  ]
}
```

Currently this is not allowed as the `ServiceBusMessageOutConverter` only allows for a `str` or `bytes` type. I converted both methods `encode` and `check_output_type_annotation` to allow for collections in a similar fashion to the [Queue Binding](https://github.com/Azure/azure-functions-python-library/blob/dev/azure/functions/queue.py) and when I run the function locally it is able to create multiple output messages to the same binding. 

Is this something that can easily be added to the library (I would be willing to submit a PR) or is this approach breaking something?

**Comment by ijoosong** [comment]
For the time being, instead of using the Output Binding, could you try doing this with the SDK and report back? This [link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/servicebus/azure-servicebus/samples/sync_samples/send_queue.py) should have everything  you need to be able to send multiple messages from within the azure function without using the output bindings!

**Comment by Hazhzeng** [comment]
Currently we don't have plan to support multiple service bus output message.
As @ijoosong mentioned, the best bet is to use our [azure-servicebus](https://pypi.org/project/azure-servicebus/) package. It provides full service bus integration. Follow the link ijoosong provided to access the example code.
