### ISSUE TITLE
Trigger refusing the sync of deployed azure function (WSGI)

### ISSUE THREAD

**Issue by jakemckenzie** [Azure/azure-functions-python-library#80]
I made an azure function that uses the [WSGI support in azure functions](https://github.com/Azure/azure-functions-python-library/pull/45). It's a simple python application that uses flask and chatterbot library to run a chatbot in the browser. The project runs fine locally but when I deploy it to Azure (runtime version 3.0.15149.0 running python 3.7.9 USGovVirginiaLinuxDynamicPlan) the triggers refuse to sync after following the instructions of the author. 

I thought I had found a workaround but I was mistaken and was wondering if anyone could point me in the right direction. 

Here is my function.json:

```
{
  "scriptFile": "__init__.py",  
  "bindings": [  
    {  
      "route": "/{*route}",
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ]
}
```

My route uses a wildcard catch-all per the author's instructions. Also, like the author, I made the routeprefix blank (to remove the "api" prefix). This is the output I end up getting at the end of my deployment

```
4:45:27 AM chatterbot: Number of duplicate files found 698
4:45:27 AM chatterbot: Number of inodes 14092
4:45:27 AM chatterbot: Number of files 12722
4:45:27 AM chatterbot: Number of fragments 1086
4:45:27 AM chatterbot: Number of symbolic links  0
4:45:27 AM chatterbot: Number of device nodes 0
4:45:27 AM chatterbot: Number of fifo nodes 0
4:45:27 AM chatterbot: Number of socket nodes 0
4:45:27 AM chatterbot: Number of directories 1370
4:45:28 AM chatterbot: Number of ids (unique uids + gids) 1
4:45:28 AM chatterbot: Number of uids 1
4:45:28 AM chatterbot: 	root (0)
4:45:28 AM chatterbot: Number of gids 1
4:45:28 AM chatterbot: 	root (0)
4:45:28 AM chatterbot: Uploading built content /home/site/artifacts/functionappartifact.squashfs for linux consumption function app...
4:45:31 AM chatterbot: Resetting all workers for [removed url]
4:45:47 AM chatterbot: Syncing triggers...
4:46:06 AM chatterbot: Syncing triggers (Attempt 2/6)...
4:46:17 AM chatterbot: Syncing triggers (Attempt 3/6)...
4:46:39 AM chatterbot: Syncing triggers (Attempt 4/6)...
4:47:19 AM chatterbot: Syncing triggers (Attempt 5/6)...
4:48:57 AM chatterbot: Syncing triggers (Attempt 6/6)...
4:48:59 AM: Error: Encountered an error (InternalServerError) from host runtime.
```
It attempts to sync the triggers a few times and fails. I'm not sure if this is an issue specific to the Linux deployment of USGov or if the route wildcard required to get this WSGI functionality is not supported but if anyone had any pointers I would appreciate it.

**Comment by tonybaloney** [comment]
Hi @jakemckenzie are you able to share the line in `__init__.py` that assigns the `main` variable?

**Comment by Hazhzeng** [comment]
I just tested out this deployment route on an Linux Consumption app and seems it is working as expected.
![image](https://user-images.githubusercontent.com/48038149/116479854-2dcbdc00-a835-11eb-99fc-348fe0a3dc77.png)

Hi @jakemckenzie, the issue you encountered should be a transient network issue.
If not, please check if your host.json has the **extensions** section as below. Thanks
```json
{
    "version":  "2.0",
    "extensions": {
        "http": {
            "routePrefix": ""
        }
    }
}
```

**Comment by jakemckenzie** [comment]
I just wanted to check in with the author. I was able to fix this issue by recreating the project within the azure portal. The module and instructions the author gave were perfect. Thank you for your time and I will close now.
