### ISSUE TITLE
HTTP Request/Response headers should be multidict

### ISSUE THREAD

**Issue by chiwanpark** [Azure/azure-functions-python-library#87]
Currently, all headers in request and response is dict. However, it should be multidict because there can be multiple items with the same key in HTTP headers. (i.e. multiple `Set-Cookie` headers to store multiple cookies)

The werkzeug implementation is based on custom implemented multidict. 

https://github.com/Azure/azure-functions-python-library/blob/3e76b293505f037dba0bd42ae19688f4fe992c67/azure/functions/_thirdparty/werkzeug/datastructures.py#L928-L930

**Comment by Ousret** [comment]
Hi,

There might be a better option than multi-dict. https://github.com/Ousret/kiss-headers

**Comment by YunchuWang** [comment]
released in 4.9.1
